import { useEffect, useMemo, useRef, useState, type KeyboardEvent } from "react";
import { createPortal } from "react-dom";
import type { DirectorMessageExchange, DirectorPreferences, DirectorProposal } from "../../api";
import type { DirectorWorkspaceState } from "./directorTypes";
import { AssetPreviewPlayer } from "./AssetPreviewPlayer";
import { DirectorContextBar } from "./DirectorContextBar";
import { ProposalCandidateCard } from "./ProposalCandidateCard";
import { ProposalComparisonTray } from "./ProposalComparisonTray";
import { candidateIdsForScope, type DirectorApplyScope } from "./director-apply-scope";
import { useDirectorReducedMotion, useResponsiveDirector } from "./useResponsiveDirector";

export type DirectorWorkspaceProps = { state: DirectorWorkspaceState; projectId: string; sessionId: string; sessionRevision: number; selectedSegment?: { segmentId: string; startSec: number; endSec: number; draftApplied: boolean }; proposal: DirectorProposal | null; sendMessage: (text: string) => Promise<unknown>; preflightProposal: (proposalId: string) => Promise<{ status?: string; code?: string; diff?: Record<string, unknown> }>; refreshProposal?: (proposalId: string) => Promise<void>; updatePreferences?: (payload: DirectorPreferences) => Promise<void>; materializeCandidate: (proposalId: string, candidateId: string) => Promise<unknown>; applyProposal: (proposalId: string, payload: { candidate_ids: string[]; expected_revision: number }) => Promise<unknown>; batchApplyProposal?: (proposalId: string, payload: { candidate_ids: string[]; expected_revision: number }) => Promise<unknown>; onManualMode: () => void };

export function DirectorWorkspace({ state, projectId: _projectId, sessionId: _sessionId, sessionRevision, selectedSegment, proposal, sendMessage, preflightProposal, refreshProposal, updatePreferences, materializeCandidate, applyProposal, batchApplyProposal, onManualMode }: DirectorWorkspaceProps) {
  const isNarrow = useResponsiveDirector();
  const reducedMotion = useDirectorReducedMotion();
  const [isOpen, setIsOpen] = useState(false); const [isCollapsed, setIsCollapsed] = useState(false);
  const openButton = useRef<HTMLButtonElement>(null); const backButton = useRef<HTMLButtonElement>(null); const desktopCollapseButton = useRef<HTMLButtonElement>(null); const sheet = useRef<HTMLElement>(null); const shouldReturnFocus = useRef(false); const wasNarrow = useRef(isNarrow);
  const [text, setText] = useState(""); const [exchange, setExchange] = useState<DirectorMessageExchange | null>(null); const [selected, setSelected] = useState<string[]>(() => proposal?.candidates[0] ? [proposal.candidates[0].candidate_id] : []); const [applyScope, setApplyScope] = useState<DirectorApplyScope>("selected_references"); const [applying, setApplying] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [preflight, setPreflight] = useState<{ status?: string; code?: string; diff?: Record<string, unknown> } | null>(null); const [retryAfter, setRetryAfter] = useState<number | null>(null); const [directorDraftApplied, setDirectorDraftApplied] = useState(false);
  const candidates = proposal?.candidates ?? [];
  const candidateIdentity = candidates.map((candidate) => candidate.candidate_id).join("|");
  useEffect(() => { setSelected(candidates[0] ? [candidates[0].candidate_id] : []); setApplyScope("selected_references"); }, [proposal?.proposal_id, candidateIdentity]);
  useEffect(() => { if (!isNarrow) setIsOpen(false); }, [isNarrow]);
  useEffect(() => { if (!isOpen && shouldReturnFocus.current) { openButton.current?.focus(); shouldReturnFocus.current = false; } }, [isOpen]);
  useEffect(() => { if (wasNarrow.current && !isNarrow) desktopCollapseButton.current?.focus(); wasNarrow.current = isNarrow; }, [isNarrow]);
  useEffect(() => {
    if (!isNarrow || !isOpen) return;
    backButton.current?.focus();
    const containFocus = (event: FocusEvent) => { if (event.target instanceof Node && !sheet.current?.contains(event.target)) backButton.current?.focus(); };
    document.addEventListener("focusin", containFocus);
    return () => document.removeEventListener("focusin", containFocus);
  }, [isNarrow, isOpen]);
  useEffect(() => {
    if (!isNarrow || !isOpen) return;
    const backgroundRoots = Array.from(document.body.children).filter((node) => !node.hasAttribute("data-director-modal-layer"));
    const saved = backgroundRoots.map((node) => ({ node, ariaHidden: node.getAttribute("aria-hidden"), inert: (node as HTMLElement & { inert?: boolean }).inert === true }));
    const blockBackground = (event: Event) => { event.preventDefault(); event.stopImmediatePropagation(); if (event.type === "focusin") backButton.current?.focus(); };
    backgroundRoots.forEach((node) => { node.setAttribute("aria-hidden", "true"); node.setAttribute("inert", ""); (node as HTMLElement & { inert?: boolean }).inert = true; ["click", "pointerdown", "keydown", "focusin"].forEach((type) => node.addEventListener(type, blockBackground, true)); });
    return () => saved.forEach(({ node, ariaHidden, inert }) => { ["click", "pointerdown", "keydown", "focusin"].forEach((type) => node.removeEventListener(type, blockBackground, true)); if (ariaHidden === null) node.removeAttribute("aria-hidden"); else node.setAttribute("aria-hidden", ariaHidden); node.toggleAttribute("inert", inert); (node as HTMLElement & { inert?: boolean }).inert = inert; });
  }, [isNarrow, isOpen]);
  const effectiveState = applying ? "applying" : state;
  useEffect(() => { let cancelled = false; setPreflight(null); if (!proposal) return; void preflightProposal(proposal.proposal_id).then((result) => { if (!cancelled) { setPreflight(result); if (result.code === "stale_proposal" || result.status === "stale") setNotice("제안이 오래되어 새로고침이 필요합니다."); } }).catch(() => { if (!cancelled) setNotice("사전 확인에 실패했습니다."); }); return () => { cancelled = true; }; }, [proposal?.proposal_id, preflightProposal]);
  const candidateIdsToApply = candidateIdsForScope(applyScope, selected, candidates);
  const canApply = Boolean(proposal && preflight && preflight.code !== "stale_proposal" && preflight.status !== "stale" && exchange?.action_intent?.target.source === "proposal" && exchange.action_intent.proposal_preflight?.proposal_id === proposal.proposal_id && candidateIdsToApply.length);
  const previews = useMemo(() => candidates.map((candidate) => ({ candidateId: candidate.candidate_id, referenceCode: candidate.visible_reference_code, mediaType: candidate.media_type, controls: candidate.controls })), [candidates]);
  async function submit() { if (!text.trim() || retryAfter !== null) return; const result = await sendMessage(text); const response = result as { kind?: string; exchange?: DirectorMessageExchange; retryAfterSeconds?: number }; if (response.kind === "in_progress" && response.retryAfterSeconds) { setRetryAfter(response.retryAfterSeconds); setNotice(`${response.retryAfterSeconds}초 뒤에 같은 메시지로 재시도할 수 있습니다.`); window.setTimeout(() => setRetryAfter(null), response.retryAfterSeconds * 1000); return; } if (response.kind === "exchange" && response.exchange) { setText(""); setExchange(response.exchange); } }
  async function apply() { if (!proposal || !candidateIdsToApply.length || !canApply || applying) return; if (candidateIdsToApply.length > 1 && !batchApplyProposal) { setNotice("일괄 적용 기능을 사용할 수 없어 여러 후보를 적용하지 않았습니다."); return; } setApplying(true); try { const latestPreflight = await preflightProposal(proposal.proposal_id); setPreflight(latestPreflight); if (latestPreflight.code === "stale_proposal" || latestPreflight.status === "stale") { setNotice("제안이 오래되어 적용하지 않았습니다."); return; } if (batchApplyProposal) await batchApplyProposal(proposal.proposal_id, { candidate_ids: candidateIdsToApply, expected_revision: sessionRevision }); else { await materializeCandidate(proposal.proposal_id, candidateIdsToApply[0]); await applyProposal(proposal.proposal_id, { candidate_ids: [candidateIdsToApply[0]], expected_revision: sessionRevision }); } setDirectorDraftApplied(true); setNotice("변경을 적용했습니다."); } catch { setNotice("적용에 실패했습니다. 수동 편집은 계속할 수 있습니다."); } finally { setApplying(false); } }
  function closeSheet() { shouldReturnFocus.current = true; setIsOpen(false); }
  function trapFocus(event: KeyboardEvent<HTMLElement>) { if (event.nativeEvent.isComposing) return; if (event.key === "Escape") { event.preventDefault(); closeSheet(); return; } if (event.key !== "Tab") return; const focusables = sheet.current?.querySelectorAll<HTMLElement>("button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [href], [tabindex]:not([tabindex='-1']):not([disabled]), audio[controls]:not([disabled]), video[controls]:not([disabled])"); if (!focusables?.length) return; const first = focusables[0]; const last = focusables[focusables.length - 1]; if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } else if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } }
  const timecode = selectedSegment ? `${selectedSegment.startSec.toFixed(2)}–${selectedSegment.endSec.toFixed(2)}` : undefined;
  const body = <><DirectorContextBar segmentId={selectedSegment?.segmentId ?? proposal?.target_segment_ids[0]} timecode={timecode} placement={proposal?.revision_code} revision={proposal ? `revision ${proposal.base_session_revision}` : undefined} draftApplied={selectedSegment?.draftApplied || directorDraftApplied} /><p role="status" aria-live="polite">상태: {effectiveState}</p>{state === "script_required" ? <p>스크립트가 필요합니다.</p> : null}{state === "blocked" || state === "error" ? <button type="button" onClick={onManualMode}>수동 편집 계속</button> : null}<label>디렉터 메시지<textarea aria-label="디렉터 메시지" value={text} onChange={(event) => setText(event.target.value)} /></label><button type="button" disabled={retryAfter !== null} onClick={() => void submit()}>보내기</button>{retryAfter !== null ? <button type="button" disabled>재시도 대기 {retryAfter}초</button> : null}{exchange ? <article><p>{exchange.assistant_message.text}</p>{exchange.action_intent ? <p>제안 의도: {exchange.action_intent.action}</p> : null}</article> : null}{proposal ? <><ProposalComparisonTray proposal={proposal} selectedIds={candidateIdsToApply} preflight={preflight} /><fieldset aria-label="적용 범위"><legend>적용 범위</legend><label><input type="radio" name="director-apply-scope" checked={applyScope === "selected_references"} onChange={() => setApplyScope("selected_references")} />선택 참조 범위</label><label><input type="radio" name="director-apply-scope" checked={applyScope === "broll_only"} onChange={() => setApplyScope("broll_only")} />B-roll 범위</label><label><input type="radio" name="director-apply-scope" checked={applyScope === "all"} onChange={() => setApplyScope("all")} />전체 범위</label></fieldset><div className="director-candidate-tray" aria-label="후보 캐러셀" data-responsive-candidate-tray={isNarrow ? "carousel" : "list"}>{candidates.map((candidate) => <ProposalCandidateCard key={candidate.candidate_id} candidate={candidate} selected={selected.includes(candidate.candidate_id)} onToggle={(id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])} onPreference={updatePreferences ? (kind, value) => void updatePreferences({ [kind]: [value] }) : undefined} />)}</div><AssetPreviewPlayer proposalId={proposal.proposal_id} candidates={previews} previewUrl={(id) => `/api/projects/${_projectId}/director/proposals/${proposal.proposal_id}/candidates/${encodeURIComponent(id)}/preview`} /><button type="button" disabled={!canApply || applying} onClick={() => void apply()}>변경 적용</button>{preflight?.code === "stale_proposal" || preflight?.status === "stale" ? <button type="button" onClick={() => refreshProposal && void refreshProposal(proposal.proposal_id)}>제안 새로고침</button> : null}</> : null}{notice ? <p role="status" aria-live="polite">{notice}</p> : null}</>;
  if (isNarrow) { const modal = isOpen && typeof document !== "undefined" ? createPortal(<div className="director-modal-layer" data-director-modal-layer onMouseDown={(event) => { if (event.target === event.currentTarget) closeSheet(); }}><aside ref={sheet} className="director-sheet" role="dialog" aria-modal="true" aria-label="Local Media Director" data-reduced-motion={reducedMotion} onKeyDown={trapFocus}><header><button ref={backButton} type="button" onClick={closeSheet}>뒤로</button><h2>Local Media Director</h2></header>{body}<button type="button" onClick={closeSheet}>닫기</button></aside></div>, document.body) : null; return <section className="director-responsive-shell" aria-label="Local Media Director"><button ref={openButton} type="button" aria-expanded={isOpen} onClick={() => setIsOpen(true)}>디렉터 열기</button>{modal}{!isOpen ? <p role="status" aria-live="polite">디렉터 패널이 닫혀 있습니다.</p> : null}</section>; }
  return <aside className={`director-aside${isCollapsed ? " is-collapsed" : ""}`} aria-label="Local Media Director" data-state={effectiveState}><div className="director-aside-header"><h2>Local Media Director</h2><button ref={desktopCollapseButton} type="button" aria-expanded={!isCollapsed} onClick={() => setIsCollapsed((value) => !value)}>{isCollapsed ? "디렉터 펼치기" : "디렉터 접기"}</button></div>{isCollapsed ? <p role="status">디렉터 패널이 접혀 있습니다.</p> : body}</aside>;
}
