from __future__ import annotations

import re

from videobox_storage.sqlite_schema import PROJECT_SCHEMA_STATEMENTS


_PROJECT_SCOPED_IDENTIFIERS = {
    "assets": "asset_id",
    "editing_sessions": "session_id",
    "exports": "export_id",
    "jobs": "job_id",
    "preview_renders": "preview_id",
    "review_approvals": "timeline_id",
    "recommendations": "recommendation_id",
    "segment_analysis_runs": "segment_analysis_id",
    "segments": "segment_id",
    "subtitle_renders": "subtitle_id",
    "timelines": "timeline_id",
    "transcripts": "transcript_id",
    "tts_candidates": "candidate_id",
}


def _postgres_statement(statement: str) -> str:
    converted = statement.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    table_match = re.search(r"CREATE TABLE IF NOT EXISTS ([a-z_]+)", converted)
    if table_match is None:
        return converted
    table_name = table_match.group(1)
    identifier = _PROJECT_SCOPED_IDENTIFIERS.get(table_name)
    if identifier is None:
        return converted
    converted = converted.replace(f"{identifier} TEXT PRIMARY KEY", f"{identifier} TEXT NOT NULL")
    return re.sub(
        r"\n\s*\)\s*$",
        f",\n        PRIMARY KEY (project_id, {identifier})\n    )",
        converted,
    )


POSTGRES_SCHEMA_STATEMENTS = tuple(_postgres_statement(statement) for statement in PROJECT_SCHEMA_STATEMENTS)

POSTGRES_MIGRATION_STATEMENTS = (
    "DROP TABLE IF EXISTS " + "g" + "emini_provider_keys",
    "ALTER TABLE creation_briefs ADD COLUMN IF NOT EXISTS summary_text TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE creation_briefs ADD COLUMN IF NOT EXISTS script_asset_owned INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE director_messages ADD COLUMN IF NOT EXISTS metadata_json TEXT NOT NULL DEFAULT '{}'",
    "ALTER TABLE director_message_claims ADD COLUMN IF NOT EXISTS owner_token TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE director_message_claims ADD COLUMN IF NOT EXISTS heartbeat_at TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS decision_state TEXT",
    "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_percent INTEGER",
    "ALTER TABLE editing_sessions ADD COLUMN IF NOT EXISTS session_revision INTEGER NOT NULL DEFAULT 1",
    "ALTER TABLE editing_sessions ADD COLUMN IF NOT EXISTS session_json TEXT NOT NULL DEFAULT '{}'",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS technical_status TEXT NOT NULL DEFAULT 'legacy_unverified'",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS operator_review_status TEXT NOT NULL DEFAULT 'pending'",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS target_duration_sec DOUBLE PRECISION",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS actual_duration_sec DOUBLE PRECISION",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS failure_code TEXT",
    *(
        f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {declaration}"
        for table in ("review_approvals", "preview_renders", "subtitle_renders", "exports")
        for column, declaration in (
            ("source_session_id", "TEXT"),
            ("source_session_revision", "INTEGER"),
            ("is_current", "INTEGER NOT NULL DEFAULT 1"),
            ("invalidated_at", "TEXT"),
            ("invalidated_reason", "TEXT"),
        )
    ),
    *(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = '{table}'::regclass
                  AND contype = 'p'
                  AND pg_get_constraintdef(oid) <> 'PRIMARY KEY (project_id, {identifier})'
            ) THEN
                EXECUTE 'ALTER TABLE {table} DROP CONSTRAINT {table}_pkey';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = '{table}'::regclass AND contype = 'p'
            ) THEN
                EXECUTE 'ALTER TABLE {table} ADD PRIMARY KEY (project_id, {identifier})';
            END IF;
        END $$
        """
        for table, identifier in _PROJECT_SCOPED_IDENTIFIERS.items()
    ),
)

POSTGRES_IMPORT_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS videobox_snapshot_imports (
        project_id TEXT PRIMARY KEY,
        source_sha256 TEXT NOT NULL,
        imported_at TEXT NOT NULL
    )
    """,
)
