from __future__ import annotations

import re

from videobox_storage.sqlite_schema import (
    ARTIFACT_SOURCE_SESSION_BACKFILL_STATEMENTS,
    PROJECT_SCHEMA_STATEMENTS,
)


_PROJECT_SCOPED_IDENTIFIERS = {
    "assets": "asset_id",
    "editing_sessions": "session_id",
    "output_variants": "variant_id",
    "variant_materializations": "materialization_id",
    "exports": "export_id",
    "jobs": "job_id",
    "preview_renders": "preview_id",
    "review_approvals": "timeline_id",
    "recommendations": "recommendation_id",
    "segment_analysis_runs": "segment_analysis_id",
    "segments": "segment_id",
    "subtitle_renders": "subtitle_id",
    "timelines": "timeline_id",
    "transcripts": "transcript_id",
    "tts_candidates": "candidate_id",
    "yujin_memory_candidates": "candidate_id",
    "yujin_memory_candidate_audit": "audit_event_id",
    "yujin_memory_operation_audit": "operation_audit_id",
}


def _postgres_statement(statement: str) -> str:
    converted = statement.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    table_match = re.search(r"CREATE TABLE IF NOT EXISTS ([a-z_]+)", converted)
    if table_match is None:
        return converted
    table_name = table_match.group(1)
    identifier = _PROJECT_SCOPED_IDENTIFIERS.get(table_name)
    if identifier is None:
        return converted
    converted = converted.replace(f"{identifier} TEXT PRIMARY KEY", f"{identifier} TEXT NOT NULL")
    return re.sub(
        r"\n\s*\)\s*$",
        f",\n        PRIMARY KEY (project_id, {identifier})\n    )",
        converted,
    )


POSTGRES_SCHEMA_STATEMENTS = tuple(_postgres_statement(statement) for statement in PROJECT_SCHEMA_STATEMENTS)

POSTGRES_MIGRATION_STATEMENTS = (
    "DROP TABLE IF EXISTS " + "g" + "emini_provider_keys",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS lifecycle_version TEXT NOT NULL DEFAULT 'legacy_retired'",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS conversation_id TEXT",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS run_id TEXT",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS session_id TEXT",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS session_revision INTEGER",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS asset_index_revision INTEGER",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS action TEXT",
    "ALTER TABLE hermes_capability_ledger ADD COLUMN IF NOT EXISTS updated_at TEXT",
    "UPDATE hermes_capability_ledger SET updated_at = recorded_at WHERE updated_at IS NULL",
    "ALTER TABLE hermes_capability_ledger ALTER COLUMN updated_at SET NOT NULL",
    "DROP INDEX IF EXISTS idx_hermes_capability_ledger_scope",
    """
    CREATE UNIQUE INDEX IF NOT EXISTS uq_hermes_capability_v1_scope_action
    ON hermes_capability_ledger (
        project_id, conversation_id, run_id, action
    )
    WHERE lifecycle_version = 'videobox.yujin-capability.v1'
    """,
    "ALTER TABLE creation_briefs ADD COLUMN IF NOT EXISTS summary_text TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE creation_briefs ADD COLUMN IF NOT EXISTS script_asset_owned INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE director_messages ADD COLUMN IF NOT EXISTS metadata_json TEXT NOT NULL DEFAULT '{}'",
    "ALTER TABLE director_messages ADD COLUMN IF NOT EXISTS message_order BIGINT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS external_ref TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS operation_id TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS provider_event_ref TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS provider_memory_ref TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS store_client_request_id TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS write_claim_token TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS write_claimed_at TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS provider_call_started_at TEXT",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE yujin_memory_candidates ADD COLUMN IF NOT EXISTS storage_status TEXT NOT NULL DEFAULT 'not_requested'",
    """
    WITH ordered AS (
        SELECT ctid,
               ROW_NUMBER() OVER (
                   PARTITION BY conversation_id
                   ORDER BY created_at, ctid
               ) AS message_order
        FROM director_messages
        WHERE message_order IS NULL
    )
    UPDATE director_messages AS message
    SET message_order = ordered.message_order
    FROM ordered
    WHERE message.ctid = ordered.ctid
    """,
    "ALTER TABLE director_messages ALTER COLUMN message_order SET NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS director_messages_conversation_order_idx ON director_messages (conversation_id, message_order)",
    "ALTER TABLE director_message_claims ADD COLUMN IF NOT EXISTS owner_token TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE director_message_claims ADD COLUMN IF NOT EXISTS heartbeat_at TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS expected_session_revision INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS expected_asset_index_revision INTEGER NOT NULL DEFAULT -1",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS selected_segment_id TEXT",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS retry_of_run_id TEXT",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS assistant_draft_text TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS next_event_id INTEGER NOT NULL DEFAULT 1",
    "ALTER TABLE director_hermes_runs ADD COLUMN IF NOT EXISTS events_pruned_at TEXT",
    """
    INSERT INTO director_hermes_run_events (
        project_id, run_id, event_id, event_type, text, retryable, created_at
    )
    SELECT run.project_id, run.run_id, 1, 'run_started', '', 0, run.created_at
    FROM director_hermes_runs AS run
    WHERE run.next_event_id = 1 AND run.events_pruned_at IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM director_hermes_run_events AS event
          WHERE event.project_id = run.project_id AND event.run_id = run.run_id
      )
    ON CONFLICT DO NOTHING
    """,
    """
    INSERT INTO director_hermes_run_events (
        project_id, run_id, event_id, event_type, text, retryable, created_at
    )
    SELECT run.project_id, run.run_id, 2,
           CASE WHEN run.status = 'completed' THEN 'run_completed' ELSE 'blocked' END,
           message.text,
           CASE WHEN run.status = 'completed' THEN 0 ELSE 1 END,
           run.updated_at
    FROM director_hermes_runs AS run
    JOIN director_messages AS message
      ON message.project_id = run.project_id
     AND message.message_id = run.assistant_message_id
    WHERE run.next_event_id = 1
      AND run.status IN ('completed', 'blocked', 'interrupted')
      AND run.events_pruned_at IS NULL
    ON CONFLICT DO NOTHING
    """,
    """
    UPDATE director_hermes_runs AS run
    SET next_event_id = CASE
            WHEN run.status IN ('completed', 'blocked', 'interrupted')
                 AND EXISTS (
                     SELECT 1 FROM director_hermes_run_events AS event
                     WHERE event.project_id = run.project_id
                       AND event.run_id = run.run_id
                       AND event.event_id = 2
                 )
            THEN 3 ELSE 2 END,
        events_pruned_at = CASE
            WHEN run.status IN ('completed', 'blocked', 'interrupted')
                 AND NOT EXISTS (
                     SELECT 1 FROM director_hermes_run_events AS event
                     WHERE event.project_id = run.project_id
                       AND event.run_id = run.run_id
                       AND event.event_id = 2
                 )
            THEN run.updated_at ELSE run.events_pruned_at END
    WHERE run.next_event_id = 1
    """,
    "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS decision_state TEXT",
    "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_percent INTEGER",
    "ALTER TABLE editing_sessions ADD COLUMN IF NOT EXISTS session_revision INTEGER NOT NULL DEFAULT 1",
    "ALTER TABLE editing_sessions ADD COLUMN IF NOT EXISTS session_json TEXT NOT NULL DEFAULT '{}'",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS technical_status TEXT NOT NULL DEFAULT 'legacy_unverified'",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS operator_review_status TEXT NOT NULL DEFAULT 'pending'",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS target_duration_sec DOUBLE PRECISION",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS actual_duration_sec DOUBLE PRECISION",
    "ALTER TABLE tts_candidates ADD COLUMN IF NOT EXISTS failure_code TEXT",
    *(
        f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {declaration}"
        for table in ("review_approvals", "preview_renders", "subtitle_renders", "exports")
        for column, declaration in (
            ("source_session_id", "TEXT"),
            ("source_session_revision", "INTEGER"),
            ("is_current", "INTEGER NOT NULL DEFAULT 1"),
            ("invalidated_at", "TEXT"),
            ("invalidated_reason", "TEXT"),
        )
    ),
    *ARTIFACT_SOURCE_SESSION_BACKFILL_STATEMENTS,
    "ALTER TABLE exports ADD COLUMN IF NOT EXISTS handoff_claim_token TEXT",
    "ALTER TABLE exports ADD COLUMN IF NOT EXISTS handoff_claim_job_id TEXT",
    "ALTER TABLE exports ADD COLUMN IF NOT EXISTS handoff_claimed_at TEXT",
    "ALTER TABLE exports ADD COLUMN IF NOT EXISTS handoff_claim_expires_at TEXT",
    *(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = '{table}'::regclass
                  AND contype = 'p'
                  AND pg_get_constraintdef(oid) <> 'PRIMARY KEY (project_id, {identifier})'
            ) THEN
                EXECUTE 'ALTER TABLE {table} DROP CONSTRAINT {table}_pkey';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = '{table}'::regclass AND contype = 'p'
            ) THEN
                EXECUTE 'ALTER TABLE {table} ADD PRIMARY KEY (project_id, {identifier})';
            END IF;
        END $$
        """
        for table, identifier in _PROJECT_SCOPED_IDENTIFIERS.items()
    ),
)

POSTGRES_IMPORT_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS videobox_snapshot_imports (
        project_id TEXT PRIMARY KEY,
        source_sha256 TEXT NOT NULL,
        imported_at TEXT NOT NULL
    )
    """,
)
